### ISSUE TITLE
Pyme-omero does not work with main directory with a space

### ISSUE THREAD

**Issue by HelenSun09** [python-microscopy/pyme-omero#6]
Error message: 
Installed c:\users\helen sun\pyme-omero
Processing dependencies for pyme-omero==20.9.10
Finished processing dependencies for pyme-omero==20.9.10
'C:\Users\Helen' is not recognized as an internal or external command,
operable program or batch file.

**Comment by barentine** [comment]
Hi @HelenSun09  - sorry I'm just seeing that now. Generally spaces in the path to your python executable might run into some problems with various software packages (but I appreciate your help in making this one more robust!!)

**Comment by barentine** [comment]
should be set @HelenSun09
